- name: Get gitlab-server repo
  git:
    repo: "https://github.com/AntonioBriPerez/gitlab-serveir.git"
    dest: "~/git_repos/gitlab-server/"
    clone: yes
    update: yes
    force: yes
    version: main
    accept_hostkey: yes

- name: Start the container
  shell: |
    cd ~/git_repos/gitlab-server/ 
    docker compose up -d

- name: Start the container of samba service
  docker_compose:
    project_name: gitlab-server
    project_src: "~/git_repos/gitlab-server/"
    files: docker-compose.yml
    state: present
