- name: Get gitlab-server repo
  git:
    repo: "https://github.com/AntonioBriPerez/gitlab-server.git"
    dest: "~/git_repos/gitlab-server/"
    clone: yes
    update: yes
    force: yes
    version: main
    accept_hostkey: yes

- name: Start the container of gitlab service
  docker_compose:
    project_name: gitlab-server
    project_src: "~/git_repos/gitlab-server/"
    files: docker-compose.yml
    state: present
