# playbook.yml
---
- name: Install Nginx on web server
  hosts: portainer
  become: true
  tasks:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
    