- name: Configure linux workstation server on machine
  hosts: docker_servers
  become: true
  gather_facts: false
  tasks:
    - name: Install and configure Docker
      include_role:
        name: docker
