- name: Install and deploy samba server on machine
  hosts: nextcloud_server
  become: true
  gather_facts: false
  tasks:
    - name: Configure hard drive mount
      include_role:
        name: hard_drive_mount
      vars:
        source_volume: /dev/vda
        mount_point: /mnt/ocean
