- name: Prepare proxmox host
  hosts: proxmox
  gather_facts: false
  become: true
  tasks:
    - name: Add disk to the machine
      shell: /sbin/qm set 101 -virtio2 /dev/disk/by-id/ata-ST3000DM001-1CH166_Z1F4C8RS-part2
      register: shell_output
    - name: Display added HDD to VM in proxmox server
      debug:
        var: shell_output.stdout_lines

- name: Install and deploy plex server on machine
  hosts: plex_server
  become: true
  gather_facts: false
  tasks:
    - name: Configure hard drive mount
      include_role:
        name: hard_drive_mount

    - name: Install and configure Docker
      include_role:
        name: docker

    - name: Get plex-server repo
      git:
        repo: https://github.com/AntonioBriPerez/plex-server
        dest: ~/git_repos/plex-server

    - name: Generate .env file
      copy:
        dest: ~/git_repos/plex-server/.env
        content: |
          MEDIA=/mnt/ocean/antonio_hdd_3tb/PlexServer
          STORAGE=/mnt/ocean/antonio_hdd_3tb/PlexServer/Downloads/torrents
          ROOT=/mnt/ocean/antonio_hdd_3tb/

    - name: "Install pip packages"
      pip:
        name:
          - docker
          - PyYAML
        state: present

    - name: Start the container
      docker_compose:
        project_name: plex-server
        project_src: ~/git_repos/plex-server/
        files: docker-compose.yml
        state: present
