- name: Prepare proxmox host
  hosts: proxmox
  gather_facts: false
  become: true
  tasks:
    - name: Add disk to the machine
      shell: /sbin/qm set 100 -virtio2 /dev/disk/by-id/ata-ST3000DM001-1CH166_Z1F4C8RS-part2
      register: shell_output
    - name: Display added HDD to VM in proxmox server
      debug:
        var: shell_output.stdout_lines

- name: Install and deploy samba server on machine
  hosts: samba_server
  become: true
  gather_facts: false
  tasks:
    - name: Configure hard drive mount
      include_role:
        name: hard_drive_mount

    - name: Install and configure Docker
      include_role:
        name: docker

    - name: Copy private key to remote host
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        mode: "0600" #otherwise ssh key will not work

    - name: Get samba-server repo
      git:
        repo: git@github.com:AntonioBriPerez/samba-server.git
        dest: ~/git_repos/samba-server
        key_file: ~/.ssh/id_rsa
        accept_hostkey: true

    - name: Generate .env file
      copy:
        dest: ~/git_repos/samba-server/.env
        content: |
          ROOT=/mnt/ocean/antonio_hdd_3tb

    - name: "Install pip packages"
      pip:
        name:
          - docker
          - PyYAML
        state: present

    - name: Start the container
      docker_compose:
        project_name: samba-server
        project_src: ~/git_repos/samba-server/
        files: docker-compose.yml
        state: present

    - name: Remove file
      file:
        path: ~/.ssh/id_rsa #preventing stealing ssh key so we remove it
        state: absent
