---
# This playbook fetches a secret from Akeyless Vault
- name: Echo
  hosts: plex_server
  tasks:
   - name: Fetching a secret named test from Akeyless Vault
     debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/data/MyFirstSecret:data') }}"

