---
# This playbook fetches a secret from Akeyless Vault
- name: Echo
  hosts: plex_server
  tasks:
  - name: Fetching a secret named test from Akeyless Vault
    set_fact: 
      secret: "{{ lookup('hashi_vault', 'secret=secret/DevOps/Ansible' ) }}" 
    register: output
  
  - name: Print registered output
    debug:
      msg: "{{ secret.values() }}"
