---
# This playbook fetches a secret from Akeyless Vault
- name: Echo
  hosts: plex_server
  tasks:
   - name: Fetching a secret named test from Akeyless Vault
     debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/DevOps/Ansible' ) }}"

# VAULT_TOKEN=$(akeyless auth --access-id "p-9cert7yh4pn3" --access-type="access_key" --access-key "QlNWqhJRAG9qt5cULFGw7rB1FwHTi+49Dbk+7oq49gE=" --json true | awk '/token/ { gsub(/[",]/,"",$2); print $2}' > ~/.vault-token)