- name: Install and deploy wireguard server on machine
  hosts: wireguard_server
  become: true
  vars:
    repo_url: https://github.com/AntonioBriPerez/wireguard-vpn
    repo_route: ~/git_repos/wireguard-server/

  tasks:
    - name: Get wireguard-server repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_route }}"

    - name: "Install pip packages"
      pip:
        name:
          - docker
          - PyYAML
        state: present

    - name: Start the container
      docker_compose:
        project_name: wireguard-server
        project_src: "{{ repo_route }}"
        files: docker-compose.yml
        state: present
