- name: Install and deploy wireguard server on machine
  hosts: wireguard_server
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: "Install prerequesites"
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - pip
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: "Install Docker packages"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present

    - name: "Create group Docker"
      group:
        name: docker

    - name: Add user antonio to group mygroup
      user:
        name: antonio
        groups: docker

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted

    - name: Get wireguard-server repo
      git:
        repo: https://github.com/AntonioBriPerez/wireguard-vpn
        dest: ~/git_repos/wireguard-server

    - name: "Install pip packages"
      pip:
        name:
          - docker
          - PyYAML
        state: present

    - name: Start the container
      docker_compose:
        project_name: wireguard-server
        project_src: ~/git_repos/wireguard-server/
        files: docker-compose.yml
        state: present
