# tasks/main.yml

- name: Download Zabbix repository release package
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1%2Bubuntu22.04_all.deb"
    dest: "/tmp/zabbix-release_6.4-1+ubuntu20.04_all.deb"

- name: Install Zabbix repository release package
  become: true
  apt:
    deb: "/tmp/zabbix-release_6.4-1+ubuntu20.04_all.deb"

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Zabbix Agent 2
  become: true
  apt:
    name: zabbix-agent2
    state: present

- name: Set server location
  set_fact:
    location_latitude: "{{ location_latitude }}"
    location_altitude: "{{ location_altitude }}"
  tags: location

- name: Configure Zabbix agent
  lineinfile:
    path: "{{ zabbix_agent_conf_file }}"
    line: "{{ item.line }}"
    regexp: "^#?{{ item.regexp }}"
    state: present
  loop:
    - { regexp: "Server=", line: "Server={{ zabbix_server_ip }}" }
    - { regexp: "ServerActive=", line: "ServerActive={{ zabbix_server_ip }}" }
    - { regexp: "Hostname=", line: "Hostname={{ ansible_hostname }}" }

- name: Restart Zabbix Agent 2 service
  become: true
  service:
    name: zabbix-agent2
    state: restarted
