- name: Install and deploy nextcloud server on machine
  hosts: nextcloud_server
  become: true
  gather_facts: false
  vars:
    repo_url: git@github.com:AntonioBriPerez/services.git
    repo_route: ~/git_repos/services/
    ssh_priv_key: ~/.ssh/id_rsa
    service_route: "{{ repo_route }}docker/nextcloud-server/"

  tasks:
  - name: Fetching MySQL passwords
    set_fact: 
      mysql_password: "{{ lookup('hashi_vault', 'secret=secret/nextcloud/mysql_password' ).values() | first }}" 
      mysql_root_password: "{{ lookup('hashi_vault', 'secret=secret/nextcloud/mysql_root_password' ).values() | first }}" 
  


  - name: Copy ssh private key to remote host to download git repo
    copy:
      src: "{{ ssh_priv_key }}"
      dest: "{{ ssh_priv_key }}"
      mode: "0600" #otherwise ssh key will not work

  - name: Get nextcloud repo via SSH
    git:
      repo: "{{ repo_url }}"
      dest: "{{ repo_route }}"
      key_file: "{{ ssh_priv_key }}"
      accept_hostkey: true
  
  - name: Create .env file with secrets
    copy:
      dest: "{{ service_route }}.env"
      content: |
        mysql_password={{ mysql_password}}
        mysql_root_password= {{ mysql_root_password}}

  - name: Start the container of nextcloud
    docker_compose:
      project_name: nextcloud-server
      project_src: "{{ service_route }}"
      files: docker-compose.yml
      state: present
      env_file: "{{ service_route }}.env"

  - name: Remove SSH private key file
    file:
      path: "{{ ssh_priv_key }}" #preventing stealing ssh key so we remove it
      state: absent
