- name: Prepare proxmox host
  hosts: proxmox
  gather_facts: false
  become: true
  tasks:
    - name: Add disk to the machine
      shell: /sbin/qm set "{{ hostvars['plex']['vm_id'] }}" -virtio2 /dev/disk/by-id/ata-ST3000DM001-1CH166_Z1F4C8RS-part2

      register: shell_output
    - name: Display added HDD to VM in proxmox server
      debug:
        var: shell_output.stdout_lines

- name: Install and deploy plex server on machine
  hosts: plex_server
  become: true
  gather_facts: false
  vars:
    repo_url: git@github.com:AntonioBriPerez/services.git
    repo_route: ~/git_repos/services/
    ssh_priv_key: /home/anton/.ssh/id_rsa

  tasks:
    - name: Configure hard drive mount
      include_role:
        name: hard_drive_mount
      vars:
        source_volume: /dev/vdb
        mount_point: /mnt/ocean

    - name: Copy ssh private key to remote host to download git repo
      copy:
        src: "{{ ssh_priv_key }}"
        dest: "{{ ssh_priv_key }}"
        mode: "0600" #otherwise ssh key will not work

    - name: Get plex-server repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_route }}"
        clone: true
        update: true
        force: true
        version: main
        key_file: "{{ ssh_priv_key }}"
        accept_hostkey: true

    - name: Start the container
      docker_compose:
        project_name: plex-server
        project_src: "{{ repo_route }}docker/plex-server/"
        files: docker-compose.yml
        state: present
