# configure-zabbix-server.yml
---
- name: Configure Zabbix server on target hosts
  hosts: zabbix_server
  become: true
  gather_facts: false
  tasks:
    - name: Install and configure Zabbix Server
      include_role:
        name: zabbix_server
