Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
      cpus = 4
      memory = 8192
      master.vm.network "private_network", ip: "192.168.50.10"
    end
    config.vm.define "worker1" do |worker1|
      worker1.vm.hostname = "worker1"
      cpus = 4
      memory = 8192
      worker1.vm.network "private_network", ip: "192.168.50.11"
    end
    config.vm.define "worker2" do |worker2|
      worker2.vm.hostname = "worker2"
      cpus = 4
      memory = 8192
      worker2.vm.network "private_network", ip: "192.168.50.12"
    end
  end