- name: Update apt cache
  apt:
    update_cache: yes

- name: Configure folder mnt
  file:
    path: "{{ mount_point }}"
    mode: "0755"
    state: directory

- name: Check if mount point exists
  stat:
    path: "{{ mount_point }}"
  register: mount_point_stat

- name: Mount the volume if not already mounted
  mount:
    name: "{{ mount_point }}"
    src: "{{ source_volume }}"
    fstype: ext3
    state: mounted
    opts: defaults
