---
- name: "Install prerequesites"
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - pip
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: "Install Docker packages"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: present

- name: "Create group Docker"
  group:
    name: docker

- name: Add users to docker group
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - anton
    - zabbix

- name: Remove file if it exists
  file:
    path: /etc/docker/daemon.json
    state: absent

- name: Modify ExecStart line in Docker service file
  replace:
    path: /lib/systemd/system/docker.service
    regexp: "ExecStart=/usr/bin/dockerd.*"
    replace: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375"

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: Restart Docker service
  systemd:
    name: docker.service
    state: restarted
