- name: Fetching MySQL passwords
  set_fact: 
    mysql_password: "{{ lookup('hashi_vault', 'secret=secret/zabbix/mysql_password' ).values() | first }}" 
    mysql_root_password: "{{ lookup('hashi_vault', 'secret=secret/zabbix/mysql_root_password' ).values() | first }}" 
  
- name: Copy ssh private key to remote host to download git repo
  copy:
    src: "{{ ssh_priv_key }}"
    dest: "{{ ssh_priv_key }}"
    mode: "0600" #otherwise ssh key will not work

- name: Get services repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_route }}"
    clone: yes
    update: yes
    force: yes
    key_file: "{{ ssh_priv_key }}"
    accept_hostkey: true

- name: Create .env file with secrets
  copy:
    dest: "{{ service_route }}env_vars/.MYSQL_PASSWORD"
    content: |
      {{ mysql_password}}

- name: Create .env file with secrets
  copy:
    dest: "{{ service_route }}env_vars/.MYSQL_ROOT_PASSWORD"
    content: |
      {{ mysql_password}}

- name: Start the container
  shell: |
    cd ~/git_repos/services/docker/zabbix-server/ 
    docker compose up -d

- name: Remove SSH private key file
  file:
    path: "{{ ssh_priv_key }}" #preventing stealing ssh key so we remove it
    state: absent
