- name: Configure docker package on machine
  hosts: docker_servers
  become: true
  gather_facts: false
  tasks:
    - name: Install and configure Docker
      include_role:
        name: docker

    - name: "Install pip packages for deploying container"
      pip:
        name:
          - docker
          - PyYAML
        state: present
